# -----------------------------------
# Hudson
# -----------------------------------

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = '''
--calculate the joker individual card effects
'''
position = "after"
payload = '''
--[[JOKERHUB INJECTION
Hudson needs to run this once for each card in hand]]
local is_hudson = (_card.config.center.key == "j_jokerhub_hudson")
local steps = is_hudson and #G.hand.cards or 1
for jh_i = 1, steps do
context.hand_card = is_hudson and G.hand.cards[jh_i] or nil
context.repetition = nil
--END JOKERHUB INJECTION
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = '''
if next(eval) then
                    eval.juice_card = eval.card
                    table.insert(effects, eval)
                    if next(post) then
                        for _, v in ipairs(post) do
                            table.insert(effects, v)
                        end
                    end
                    if eval.retriggers then
                        context.retrigger_joker = true
                        for rt = 1, #eval.retriggers do
                            local rt_eval, rt_post = eval_card(_card, context)
                            table.insert(effects, { eval.retriggers[rt] })
                            table.insert(effects, rt_eval)
                            if next(rt_post) then table.insert(effects, rt_post) end
                        end
                        context.retrigger_joker = nil
                    end
                end
'''
position = "after"
payload = '''
--JOKERHUB INJECTION
end
--END JOKERHUB INJECTION
'''
match_indent = true
times = 1
